//
//  NetworkData.swift
//  TalesAndSpirits
//
//  Created by Prodip Guha Roy on 2/9/20.
//  Copyright © 2020 RMIT. All rights reserved.
//

import Foundation

struct NetworkData {
    let cocktailList = """
{"drinks": [{
"strDrink":"Negroni",
"strDrinkThumb":"kpsajh1504368362.jpg",
"idDrink":"11003"
},{
"strDrink":"Whiskey Sour",
"strDrinkThumb":"upxxpq1439907580.jpg",
"idDrink":"11004"
},{
"strDrink":"Daiquiri",
"strDrinkThumb":"vcyvpq1485083300.jpg",
"idDrink":"11006"
},{
"strDrink":"Moscow Mule",
"strDrinkThumb":"x8lhp41513703167.jpg",
"idDrink":"11009"
},{
"strDrink":"Manhattan",
"strDrinkThumb":"hz7p4t1589575281.jpg",
"idDrink":"11008"
},{
"strDrink":"Dirty Martini",
"strDrinkThumb":"qvuyqw1441208955.jpg",
"idDrink":"17181"
},{
"strDrink":"Mojito",
"strDrinkThumb":"3z6xdi1589574603.jpg",
"idDrink":"11000"
},{
"strDrink":"Margarita",
"strDrinkThumb":"3z6xdi1589574603.jpg",
"idDrink":"11007"
},{
"strDrink":"Old Fashioned",
"strDrinkThumb":"vrwquq1478252802.jpg",
"idDrink":"11001"
},{
"strDrink":"Long Island Iced Tea",
"strDrinkThumb":"vrwquq1478252802.jpg",
"idDrink":"17204"
}]}
"""
    
    let detailedCocktail: [String:String] = [
        "11003" : """
        {"drinks":[{"idDrink":"11003","strDrink":"Negroni","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic","strVideo":"https://www.youtube.com/watch?v=Y4LH0FQlU8Q","strCategory":"Ordinary Drink","strIBA":"Unforgettables","strAlcoholic":"Alcoholic","strGlass":"Old-fashioned glass","strInstructions":"Stir into glass over ice, garnish and serve.","strInstructionsES":null,"strInstructionsDE":"In ein Glas u00fcber das Eis gieu00dfen, garnieren und servieren.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"negroni","strIngredient1":"Gin","strIngredient2":"Campari","strIngredient3":"Sweet Vermouth","strIngredient4":null,"strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"1 oz ","strMeasure2":"1 oz ","strMeasure3":"1 oz ","strMeasure4":null,"strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2015-08-18 15:12:07"}]}
        """,
        "11004" : """
        {"drinks":[{"idDrink":"11004","strDrink":"Whiskey Sour","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic,Alcoholic","strVideo":"https://www.youtube.com/watch?v=hFKZPzfngcU","strCategory":"Ordinary Drink","strIBA":"Unforgettables","strAlcoholic":"Alcoholic","strGlass":"Old-fashioned glass","strInstructions":"Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.","strInstructionsES":null,"strInstructionsDE":"Mit Eis schu00fctteln. In ein geku00fchltes Glas abseihen, garnieren und servieren. Wenn Sie servieren, die Zutaten in ein old-fashioned, mit Eis gefu00fclltes Glas geben.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"whiseysour","strIngredient1":"Blended whiskey","strIngredient2":"Lemon","strIngredient3":"Powdered sugar","strIngredient4":"Cherry","strIngredient5":"Lemon","strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"2 oz ","strMeasure2":"Juice of 1/2 ","strMeasure3":"1/2 tsp ","strMeasure4":"1 ","strMeasure5":"1/2 slice ","strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2017-09-02 12:45:25"}]}
        """,
        "11006" : """
        {"drinks":[{"idDrink":"11006","strDrink":"Daiquiri","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic,Beach","strVideo":null,"strCategory":"Ordinary Drink","strIBA":null,"strAlcoholic":"Alcoholic","strGlass":"Cocktail glass","strInstructions":"Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.","strInstructionsES":null,"strInstructionsDE":"Alle Zutaten in den Shaker mit Eiswu00fcrfel geben. Gut schu00fctteln. In einem geku00fchlten Cocktailglas abseihen.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"daiquiri","strIngredient1":"Light rum","strIngredient2":"Lime","strIngredient3":"Powdered sugar","strIngredient4":null,"strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"1 1/2 oz ","strMeasure2":"Juice of 1/2 ","strMeasure3":"1 tsp ","strMeasure4":null,"strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2015-08-18 15:06:37"}]}
        """,
        "11009" : """
        {"drinks":[{"idDrink":"11009","strDrink":"Moscow Mule","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,ContemporaryClassic","strVideo":null,"strCategory":"Punch / Party Drink","strIBA":"Contemporary Classics","strAlcoholic":"Alcoholic","strGlass":"Copper Mug","strInstructions":"Combine vodka and ginger beer in a highball glass filled with ice. Add lime juice. Stir gently. Garnish.","strInstructionsES":null,"strInstructionsDE":"Mischen Sie Wodka und Ingwerbier in einem mit Eis gefu00fcllten Highball-Glas. Limettensaft hinzufu00fcgen. Vorsichtig umru00fchren. Garnieren.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"moscowmule","strIngredient1":"Vodka","strIngredient2":"Lime juice","strIngredient3":"Ginger ale","strIngredient4":null,"strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"2 oz ","strMeasure2":"2 oz ","strMeasure3":"8 oz ","strMeasure4":null,"strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2017-09-02 17:49:48"}]}
        """,
        "11008" : """
        {"drinks":[{"idDrink":"11008","strDrink":"Manhattan","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic","strVideo":"https://www.youtube.com/watch?v=TFWPtkNoF4Y","strCategory":"Cocktail","strIBA":"Unforgettables","strAlcoholic":"Alcoholic","strGlass":"Cocktail glass","strInstructions":"Stirred over ice, strained into a chilled glass, garnished, and served up.","strInstructionsES":null,"strInstructionsDE":"u00dcber Eis geru00fchrt, in ein geku00fchltes Glas geseiht, garniert und serviert.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"manhattan","strIngredient1":"Sweet Vermouth","strIngredient2":"Bourbon","strIngredient3":"Angostura bitters","strIngredient4":"Ice","strIngredient5":"Maraschino cherry","strIngredient6":"Orange peel","strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"3/4 oz ","strMeasure2":"2 1/2 oz Blended ","strMeasure3":"dash ","strMeasure4":"2 or 3 ","strMeasure5":"1 ","strMeasure6":"1 twist of ","strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2017-09-02 12:07:09"}]}
        """,
        "17181" : """
        {"drinks":[{"idDrink":"17181","strDrink":"Dirty Martini","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,NewEra","strVideo":null,"strCategory":"Cocktail","strIBA":"New Era Drinks","strAlcoholic":"Alcoholic","strGlass":"Cocktail glass","strInstructions":"Pour the vodka, dry vermouth and olive brine into a cocktail shaker with a handful of ice and shake well.rnRub the rim of a martini glass with the wedge of lemon.rnStrain the contents of the cocktail shaker into the glass and add the olive.rnA dirty Martini contains a splash of olive brine or olive juice and is typically garnished with an olive.","strInstructionsES":null,"strInstructionsDE":"Wodka, trockenen Wermut und Olivensole in einen Cocktailshaker mit einer Handvoll Eis geben und gut schu00fctteln.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"dirtymartini","strIngredient1":"Vodka","strIngredient2":"Dry Vermouth","strIngredient3":"Olive Brine","strIngredient4":"Lemon","strIngredient5":"Olive","strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"70ml/2fl oz","strMeasure2":"1 tbsp","strMeasure3":"2 tbsp","strMeasure4":"1 wedge","strMeasure5":"1","strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"No","dateModified":"2017-01-22 11:08:20"}]}
        """,
        "11000" : """
        {"drinks":[{"idDrink":"11000","strDrink":"Mojito","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,ContemporaryClassic,Alcoholic,USA","strVideo":null,"strCategory":"Cocktail","strIBA":"Contemporary Classics","strAlcoholic":"Alcoholic","strGlass":"Highball glass","strInstructions":"Muddle mint leaves with sugar and lime juice. Add a splash of soda water and fill the glass with cracked ice. Pour the rum and top with soda water. Garnish and serve with straw.","strInstructionsES":null,"strInstructionsDE":"Minzblu00e4tter mit Zucker und Limettensaft verru00fchren. Fu00fcge einen Spritzer Sodawasser hinzu und fu00fclle das Glas mit gebrochenem Eis. Den Rum eingieu00dfen und mit Sodawasser u00fcbergieu00dfen. Garnieren und mit einem Strohhalm servieren.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"mojito","strIngredient1":"Light rum","strIngredient2":"Lime","strIngredient3":"Sugar","strIngredient4":"Mint","strIngredient5":"Soda water","strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"2-3 oz ","strMeasure2":"Juice of 1 ","strMeasure3":"2 tsp ","strMeasure4":"2-4 ","strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2016-11-04 09:17:09"}]}
        """,
        "11007" : """
        {"drinks":[{"idDrink":"11007","strDrink":"Margarita","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,ContemporaryClassic","strVideo":null,"strCategory":"Ordinary Drink","strIBA":"Contemporary Classics","strAlcoholic":"Alcoholic","strGlass":"Cocktail glass","strInstructions":"Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.","strInstructionsES":null,"strInstructionsDE":"Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der u00e4uu00dfere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genieu00dfers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schu00fctteln und vorsichtig in das Glas geben.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"margarita","strIngredient1":"Tequila","strIngredient2":"Triple sec","strIngredient3":"Lime juice","strIngredient4":"Salt","strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"1 1/2 oz ","strMeasure2":"1/2 oz ","strMeasure3":"1 oz ","strMeasure4":null,"strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2015-08-18 14:42:59"}]}
        """,
        "11001" : """
        {"drinks":[{"idDrink":"11001","strDrink":"Old Fashioned","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,Classic,Alcoholic,Expensive","strVideo":"https://www.youtube.com/watch?v=YsE_igrPXZs","strCategory":"Cocktail","strIBA":"Unforgettables","strAlcoholic":"Alcoholic","strGlass":"Old-fashioned glass","strInstructions":"Place sugar cube in old fashioned glass and saturate with bitters, add a dash of plain water. Muddle until dissolved.rnFill the glass with ice cubes and add whiskey.rnrnGarnish with orange twist, and a cocktail cherry.","strInstructionsES":null,"strInstructionsDE":"Zuckerwu00fcrfel in ein old fashioned Glas geben und mit Bitterstoff su00e4ttigen, einen Schuss Wasser hinzufu00fcgen. Vermischen, bis sie sich auflu00f6sen.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"oldfashioned","strIngredient1":"Bourbon","strIngredient2":"Angostura bitters","strIngredient3":"Sugar","strIngredient4":"Water","strIngredient5":null,"strIngredient6":null,"strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"4.5 cL","strMeasure2":"2 dashes","strMeasure3":"1 cube","strMeasure4":"dash","strMeasure5":null,"strMeasure6":null,"strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"Yes","dateModified":"2016-11-04 09:46:42"}]}
        """,
        "17204" : """
        {"drinks":[{"idDrink":"17204","strDrink":"Long Island Iced Tea","strDrinkAlternate":null,"strDrinkES":null,"strDrinkDE":null,"strDrinkFR":null,"strDrinkZH-HANS":null,"strDrinkZH-HANT":null,"strTags":"IBA,ContemporaryClassic","strVideo":null,"strCategory":"Ordinary Drink","strIBA":"Contemporary Classics","strAlcoholic":"Alcoholic","strGlass":"Highball glass","strInstructions":"Mix all contents in a highball glass and sitr gently. Add dash of Coca-Cola for the coloring and garnish with lemon or lime twist.","strInstructionsES":null,"strInstructionsDE":"Den gesamten Inhalt in einem Highball-Glas mischen und vorsichtig umru00fchren. Fu00fcr die Farbgebung einen Schuss Coca-Cola hinzufu00fcgen und mit Zitronen- oder Limettenspirale garnieren.","strInstructionsFR":null,"strInstructionsZH-HANS":null,"strInstructionsZH-HANT":null,"strDrinkThumb":"liit","strIngredient1":"Vodka","strIngredient2":"Tequila","strIngredient3":"Light rum","strIngredient4":"Gin","strIngredient5":"Coca-Cola","strIngredient6":"Lemon peel","strIngredient7":null,"strIngredient8":null,"strIngredient9":null,"strIngredient10":null,"strIngredient11":null,"strIngredient12":null,"strIngredient13":null,"strIngredient14":null,"strIngredient15":null,"strMeasure1":"1/2 oz ","strMeasure2":"1/2 oz ","strMeasure3":"1/2 oz ","strMeasure4":"1/2 oz ","strMeasure5":"1 dash ","strMeasure6":"Twist of ","strMeasure7":null,"strMeasure8":null,"strMeasure9":null,"strMeasure10":null,"strMeasure11":null,"strMeasure12":null,"strMeasure13":null,"strMeasure14":null,"strMeasure15":null,"strCreativeCommonsConfirmed":"No","dateModified":"2017-09-02 17:41:50"}]}
        """
    ]
    
}
